[phases.setup]
nixPkgs = ["zlib", "zlib.dev", "libjpeg", "libjpeg.dev", "gcc", "python311"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install --no-build-isolation -r requirements.txt"]

[start]
cmd = "python -m src.app" 