[phases.setup]
nixPkgs = ["zlib", "zlib.dev", "libjpeg", "libjpeg.dev", "gcc", "python311", "libffi", "libffi.dev", "openssl", "openssl.dev", "pkg-config"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv", 
  ". /opt/venv/bin/activate", 
  "pip install --upgrade pip wheel setuptools", 
  "pip install --only-binary=:all: -r requirements.txt"
]

[start]
cmd = "python -m src.app" 